# Generated by Django 5.0 on 2026-05-17 20:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discrepancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=255, verbose_name='Field Name')),
                ('doc1_value', models.TextField(blank=True, null=True, verbose_name='Document 1 Value')),
                ('doc2_value', models.TextField(blank=True, null=True, verbose_name='Document 2 Value')),
                ('discrepancy_type', models.CharField(choices=[('missing', 'Missing'), ('changed', 'Changed'), ('equivalent_different', 'Equivalent Different')], max_length=50, verbose_name='Discrepancy Type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('corrected', 'Corrected'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('operator_note', models.TextField(blank=True, null=True, verbose_name='Operator Note')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Discrepancy',
                'verbose_name_plural': 'Discrepancies',
                'db_table': 'discrepancies',
                'ordering': ['job', 'field_name'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=20, verbose_name='Status')),
                ('scenario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Scenario (auto-detected)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
            ],
            options={
                'verbose_name': 'Reconciliation Job',
                'verbose_name_plural': 'Reconciliation Jobs',
                'db_table': 'reconciliation_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100, verbose_name='Action')),
                ('target_model', models.CharField(max_length=100, verbose_name='Target Model')),
                ('target_id', models.CharField(max_length=100, verbose_name='Target ID')),
                ('before', models.JSONField(blank=True, null=True, verbose_name='Before')),
                ('after', models.JSONField(blank=True, null=True, verbose_name='After')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
