# Generated by Django 5.0 on 2026-05-17 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('reconciliations', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='reconciliationjob',
            name='document_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_as_doc1', to='documents.document', verbose_name='Document 1'),
        ),
        migrations.AddField(
            model_name='reconciliationjob',
            name='document_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_as_doc2', to='documents.document', verbose_name='Document 2'),
        ),
        migrations.AddField(
            model_name='reconciliationjob',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='discrepancy',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancies', to='reconciliations.reconciliationjob', verbose_name='Job'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['tenant', 'user', 'timestamp'], name='audit_logs_tenant__a23a86_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['target_model', 'target_id'], name='audit_logs_target__f350f5_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationjob',
            index=models.Index(fields=['tenant', 'status'], name='reconciliat_tenant__7e9ace_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationjob',
            index=models.Index(fields=['document_1', 'document_2'], name='reconciliat_documen_3cbcd3_idx'),
        ),
        migrations.AddIndex(
            model_name='discrepancy',
            index=models.Index(fields=['job', 'status'], name='discrepanci_job_id_a914d4_idx'),
        ),
        migrations.AddIndex(
            model_name='discrepancy',
            index=models.Index(fields=['discrepancy_type'], name='discrepanci_discrep_134c87_idx'),
        ),
    ]
