# Generated by Django 5.0 on 2026-05-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconciliationjob',
            name='scenario',
            field=models.CharField(choices=[('order_confirmation', 'Order + Confirmation'), ('price_confirmation', 'Price List + Price Confirmation'), ('unknown', 'Unknown')], default='unknown', max_length=100, verbose_name='Scenario (auto-detected)'),
        ),
    ]
