# Generated by Django 5.0 on 2026-05-17 20:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/', verbose_name='File')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('xlsx', 'Excel'), ('xls', 'Excel (Legacy)')], max_length=10, verbose_name='File Type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=20, verbose_name='Status')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('extracted_data', models.JSONField(blank=True, null=True, verbose_name='Extracted Data')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'documents',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='documents_tenant__ebc015_idx'), models.Index(fields=['tenant', 'file_type'], name='documents_tenant__f1ff8d_idx'), models.Index(fields=['uploaded_at'], name='documents_uploade_d6a956_idx')],
            },
        ),
    ]
