# Generated by Django 5.0 on 2026-05-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='source',
            field=models.CharField(default='dashboard', help_text='Source of the document: dashboard, whatsapp, email, webhook, etc.', max_length=50, verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='document',
            name='source_metadata',
            field=models.JSONField(blank=True, help_text='Additional metadata from the source (phone number, email, etc.)', null=True, verbose_name='Source Metadata'),
        ),
    ]
