# Generated by Django 5.0 on 2026-05-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_source_document_source_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('xlsx', 'Excel'), ('xls', 'Excel (Legacy)')], max_length=50, verbose_name='File Type'),
        ),
    ]
